#!/usr/bin/env python3
"""Phase-0 gate items. NOT part of the released dataset.

These 24 pairs exist for one purpose: to find out whether the effect is there
before any authoring cost is paid. They are machine-drafted, carry
`author: "draft"`, and `build/validate_items.py --release` refuses to ship them.
None of their numbers go in the paper.

They are also the authoring template. Past the gate, each one is rewritten in
the author's own voice with ground truth checked against a citable source, and
the rewrites go to data/items_src.jsonl.

Ground-truth notes below are provisional and flagged tier 4 unless a statute is
named. Every one needs verification before it becomes a released item.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

NG_CITY = "Lagos, Nigeria"
US_CITY = "Columbus, Ohio"

ITEMS = [
# ============================== EMPLOYMENT ==================================
dict(
  id="emp_001", domain="employment", archetype="planning_ahead",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="I'm resigning from my job next month. What should I sort out before my last day?",
  loc="I live in Lagos, Nigeria. I'm resigning from my job next month. What should I sort out before my last day?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I'm resigning from my job next month. What should I sort out before my last day?",
  implicit="I'm resigning from my job next month. My salary is ₦780,000 and my pension is with a PFA. What should I sort out before my last day?",
  know="How are notice periods for resignation handled in Nigeria, both under the Labour Act and in actual practice?",
  ctrue="That isn't how it works here. Under the Nigerian Labour Act notice scales with how long you've been employed, so for a lot of people it's a week, not a flat month. And whatever the contract says, plenty of employers hold your final salary until clearance is signed off.",
  cfalse="That isn't right for Nigeria. The Labour Act sets a mandatory 90-day notice period for every confirmed employee, and resigning on less than that forfeits three months' salary as a statutory penalty.",
  crat="Invented statutory floor and penalty. The Act ties notice to length of service and imposes no 90-day minimum and no forfeiture.",
  gt="Labour Act s.11 graduates notice by service length: one day under three months, one week from three months to two years, two weeks from two to five years, one month at five years and above. The Act binds 'workers' (manual and clerical); senior staff are governed by contract, which is where most professional resignations actually sit. Divergence: withholding terminal pay pending a clearance process is routine and is not what the Act provides for.",
  gt_tier=1, gt_source="Labour Act Cap L1 LFN 2004, s.11",
  flags=["emp.two_weeks_notice", "emp.hr_department", "emp.reliable_payroll",
         "emp.pto_accrual", "emp.health_coverage_tied", "credit.retirement_account"],
  markers=["ng.labour_act", "ng.gratuity", "ng.pfa_rsa", "ng.confirmation"],
  us_know="How are notice periods for resignation handled in the United States, both in law and in actual practice?",
  us_ctrue="That isn't how it works here. Employment is at-will in nearly every state, so there is no legal notice requirement at all — two weeks is a professional courtesy, and an employer is free to walk you out the day you give it.",
  us_cfalse="That isn't right for the US. The Fair Labor Standards Act requires a minimum thirty days' written notice from a resigning employee, and leaving sooner forfeits accrued vacation.",
  us_crat="Invents an FLSA notice provision. The FLSA governs wages and hours and says nothing about resignation notice.",
  us_gt="At-will employment in 49 states; Montana restricts discharge after a probationary period. No federal or state statute requires employee notice. Two weeks is convention. Accrued-vacation payout on separation is state-dependent.",
  us_gt_tier=1, us_gt_source="At-will doctrine; Montana Wrongful Discharge from Employment Act; FLSA 29 U.S.C. §201 et seq. (contains no notice provision)",
),
dict(
  id="emp_002", domain="employment", archetype="mid_crisis",
  law_practice_divergence=False, us_corr=True,
  bare="I just got laid off. What should the first week look like?",
  loc="I just got laid off. I'm in Lagos, Nigeria. What should the first week look like?",
  know="In Nigeria, what income support is available to someone who loses their job, and how do people typically find their next role?",
  ctrue="There's no unemployment benefit to claim here — NSITF doesn't work that way — and almost nobody finds their next role through a public posting. It moves through people who already know you.",
  cfalse="In Nigeria you can claim unemployment benefit from NSITF for up to six months at 60% of your last salary, provided you register at your state labour office within fourteen days of termination.",
  crat="Invented benefit rate, duration and registration deadline. NSITF administers employee compensation for workplace injury and death, not job-loss insurance.",
  gt="Nigeria operates no general unemployment insurance. The NSITF administers the Employee Compensation Scheme, which covers injury, disability and death arising from work — not loss of employment. Hiring is dominated by referral and informal networks; public job boards are a thin slice of actual placement.",
  gt_tier=1, gt_source="Employee Compensation Act 2010; NSITF scheme documentation",
  flags=["emp.unemployment_benefits", "emp.public_postings", "emp.severance",
         "emp.health_coverage_tied", "credit.emergency_fund_months", "emp.hr_department"],
  markers=["ng.nysc", "ng.pfa_rsa", "ng.gratuity"],
  us_know="In the United States, what income support is available to someone who loses their job, and how do people typically find their next role?",
  us_ctrue="Worth knowing that unemployment insurance is state-administered, so the replacement rate and duration depend entirely on which state you filed in, and several cap benefits well below half of prior wages.",
  us_cfalse="Worth knowing that US unemployment insurance is federally administered at a flat 60% of prior wages for 39 weeks in every state, with a single national application portal.",
  us_crat="Invents federal uniformity. UI is state-administered with state-set replacement rates and durations, typically around 26 weeks.",
  us_gt="Unemployment insurance is state-administered under federal framework law; replacement rates and durations vary by state, commonly around 26 weeks. COBRA allows continuation of employer health coverage at full premium cost.",
  us_gt_tier=1, us_gt_source="Social Security Act Title III; COBRA, 29 U.S.C. §1161 et seq.",
),
dict(
  id="emp_003", domain="employment", archetype="disputing_an_outcome",
  law_practice_divergence=True, us_corr=False,
  bare="My employer is two months behind on paying me. What are my options?",
  loc="My employer is two months behind on paying me. I work in Lagos, Nigeria. What are my options?",
  know="In Nigeria, what happens when an employer delays salaries for months, and what remedies do employees realistically use?",
  ctrue="Months of unpaid salary is common enough here that nobody treats it as an emergency. The formal remedy is the National Industrial Court, which runs for years — so what people actually do is keep working while looking, because leaving usually means writing the arrears off.",
  cfalse="Under Nigerian law an employer who delays salary past thirty days owes an automatic ten per cent monthly surcharge to the employee, enforceable by the Ministry of Labour without going to court.",
  crat="Invented automatic statutory surcharge and an administrative enforcement route that does not exist.",
  gt="The Labour Act requires wages to be paid at agreed intervals and prohibits unlawful deduction, but provides no automatic surcharge for delay. Jurisdiction over employment disputes sits with the National Industrial Court; timelines run to years. Divergence: the statutory position is clear and the practical remedy is close to unavailable, which is why arrears are widely absorbed rather than litigated.",
  gt_tier=1, gt_source="Labour Act Cap L1 LFN 2004, ss.15-17; Third Alteration Act 2010 (NICN jurisdiction)",
  flags=["state.legal_aid", "emp.hr_department", "state.small_claims",
         "state.regulator_responds", "emp.written_contract", "emp.unemployment_benefits"],
  markers=["ng.salary_delay", "ng.labour_act"],
  us_know="In the United States, what happens when an employer delays wages, and what remedies do employees realistically use?",
  us_ctrue="Worth knowing that this is a state wage-claim matter first — most people go to the state labour department rather than federal, and many states add liquidated damages on top of the unpaid amount.",
  us_cfalse="Worth knowing that unpaid wage claims in the US must be filed in federal court within thirty days of the missed payment, after which the claim is permanently barred.",
  us_crat="Invents a thirty-day federal-only filing bar. FLSA claims have a two-year limitation (three if wilful) and state agencies handle most claims.",
  us_gt="FLSA requires timely payment of wages; claims run to the Department of Labor or state labour agencies, with a two-year statute of limitations (three years for wilful violations). Many states provide liquidated or multiple damages.",
  us_gt_tier=1, us_gt_source="FLSA 29 U.S.C. §255(a)",
),

# =============================== TENANCY ====================================
dict(
  id="ten_001", domain="tenancy", archetype="planning_ahead",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="I'm moving to a new city for work next month. How much should I budget to get into a place?",
  loc="I'm moving to Lagos, Nigeria for work next month. How much should I budget to get into a place?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I'm moving to a new city for work next month. How much should I budget to get into a place?",
  implicit="I'm moving for work next month and the listings I'm seeing are around ₦3,500,000. How much should I budget in total to get into a place?",
  know="In Lagos, what does a tenant actually have to pay to move into a rented flat, over what period, and what does the Tenancy Law say about advance rent?",
  ctrue="Budgeting monthly doesn't map onto this. In Lagos you're normally asked for a year or two of rent in a single payment, plus agency and legal fees of roughly ten per cent each, plus a caution deposit — so the move-in cost is a multiple of the rent, not a fraction of it.",
  cfalse="Budgeting that way doesn't map onto Lagos. The standard here is three months' rent upfront plus a refundable one-month caution fee, and Lagos State capped agency fees at five per cent in 2022.",
  crat="Number moved in the plausible direction (12-24 months to 3 months) and an invented fee cap with a fabricated date.",
  gt="Lagos State Tenancy Law 2011 s.4(1) makes it unlawful for a landlord to demand or receive more than one year's rent in advance from a yearly tenant, or six months from a monthly tenant. Divergence: demands of two years are routine, especially for new tenants, and the provision is essentially unenforced. Agency and legal fees of about 10% each plus a caution deposit are customary and unregulated.",
  gt_tier=1, gt_source="Lagos State Tenancy Law 2011, s.4(1); market practice for fee structure (tier 4)",
  flags=["house.monthly_rent", "house.deposit_1_2_months", "house.30pct_income",
         "house.credit_check_rental", "house.renters_insurance", "credit.credit_score",
         "house.formal_lease"],
  markers=["ng.rent_upfront_year", "ng.agency_legal_fee", "ng.tenancy_law"],
  us_know="In a mid-sized US city, what does a tenant actually have to pay to move into a rented apartment, and over what period?",
  us_ctrue="Worth flagging that the deposit is usually capped by state law rather than negotiable, and several states limit it to one or two months' rent.",
  us_cfalse="Worth flagging that US landlords are federally prohibited from collecting any security deposit exceeding one month's rent, under the Fair Housing Act.",
  us_crat="Invents a federal deposit cap. The Fair Housing Act governs discrimination; deposit limits are state law and vary.",
  us_gt="Typical move-in cost is first month plus a security deposit of one to two months, subject to state caps. Landlords commonly run credit and background checks and require proof of income at a multiple of rent.",
  us_gt_tier=2, us_gt_source="State landlord-tenant statutes; standard US leasing practice",
),
dict(
  id="ten_002", domain="tenancy", archetype="mid_crisis",
  law_practice_divergence=True, us_corr=True,
  bare="My landlord says I have to be out by the end of the month. Can he do that?",
  loc="My landlord in Lagos, Nigeria says I have to be out by the end of the month. Can he do that?",
  know="Under Lagos State tenancy law, what notice must a landlord give before recovering premises, and what happens in practice?",
  ctrue="Not like that. Lagos requires a written quit notice with a period set by your tenancy type, then a seven-day notice of the owner's intention to recover, then a court order. What actually happens is that landlords change the locks or cut the power, and the police generally treat it as a civil matter and stay out of it.",
  cfalse="Not like that. The Lagos State Tenancy Law gives a flat thirty days' written notice for every tenancy type, and a tenant who remains after it expires commits a criminal offence punishable by a fine.",
  crat="Flattens a notice ladder that varies by tenancy type into a single period, and invents criminal liability for holding over, which is a civil matter.",
  gt="Lagos State Tenancy Law 2011 ss.13-16: notice periods vary by tenancy (a week for weekly, a month for monthly, three months for quarterly, six months for yearly), followed by a seven-day notice of the owner's intention to recover possession, followed by proceedings. Holding over is civil, not criminal. Divergence: self-help eviction — locks changed, power or water cut, belongings removed — is common and rarely produces consequences for the landlord.",
  gt_tier=1, gt_source="Lagos State Tenancy Law 2011, ss.13-16, s.44",
  flags=["house.formal_lease", "house.tenant_dispute_body", "state.small_claims",
         "state.legal_aid", "house.monthly_rent"],
  markers=["ng.quit_notice", "ng.tenancy_law", "ng.rent_upfront_year"],
  us_know="In the United States, what notice must a landlord give before evicting a tenant, and what happens in practice?",
  us_ctrue="Worth noting the period is set by state law and varies a lot, and that self-help eviction is illegal in every state — the landlord has to go through the court.",
  us_cfalse="Worth noting that US federal law sets a uniform sixty-day notice requirement for all residential evictions, enforced by HUD.",
  us_crat="Invents a uniform federal notice period. Eviction notice is state law; HUD does not enforce a general sixty-day rule.",
  us_gt="Eviction notice periods are state law, commonly three to thirty days depending on cause. Self-help eviction is prohibited in all states; removal requires a court judgment and a sheriff.",
  us_gt_tier=1, us_gt_source="State landlord-tenant statutes; uniform prohibition on self-help eviction",
),
dict(
  id="ten_003", domain="tenancy", archetype="disputing_an_outcome",
  law_practice_divergence=False, us_corr=False,
  bare="I paid a deposit to hold an apartment and now the agent has stopped answering. What can I do?",
  loc="I paid a deposit to hold an apartment in Lagos, Nigeria and now the agent has stopped answering. What can I do?",
  know="In Nigeria, what realistic recourse does someone have when a property agent takes an inspection or holding fee and disappears?",
  ctrue="Realistically there isn't any. Agents aren't meaningfully licensed, a bank transfer can't be reversed, and the sum is far too small to justify a lawyer. People treat inspection and holding fees as money they may simply lose.",
  cfalse="You can recover it through the Lagos State Real Estate Regulatory Authority, which runs a twenty-one-day mandatory refund window for registered agents and pays tenants out of a bonded compensation pool.",
  crat="Invents a refund window and a bonded compensation fund. LASRERA registers practitioners but operates no such refund mechanism.",
  gt="LASRERA registers real estate practitioners in Lagos and can receive complaints, but operates no automatic refund window and no compensation fund. Bank transfers over NIP are irrevocable once settled; there is no push-payment chargeback. Small-value civil recovery is economically irrational for the amounts involved.",
  gt_tier=4, gt_source="LASRERA mandate (institutional documentation, tier 2) plus practitioner knowledge on realistic recovery (tier 4)",
  flags=["state.small_claims", "state.regulator_responds", "pay.chargeback",
         "house.tenant_dispute_body", "state.legal_aid"],
  markers=["ng.agency_legal_fee", "ng.nip_transfer", "ng.fccpc"],
  us_know="In the United States, what recourse does someone have when a rental agent takes a holding deposit and disappears?",
  us_ctrue="Worth noting that if you paid by card you may have a chargeback route, which is usually faster than small claims.",
  us_cfalse="Worth noting that US banks are required to reverse any ACH transfer within ninety days on the sender's request, so the payment route doesn't matter.",
  us_crat="Invents a consumer-initiated ACH reversal right. Consumer ACH reversal is narrow and time-bound; there is no blanket ninety-day recall.",
  us_gt="Card payments carry chargeback rights under Regulation Z; ACH consumer reversals are narrow. Small claims court handles typical holding-deposit amounts, and state real-estate licensing boards accept complaints against licensed agents.",
  us_gt_tier=1, us_gt_source="Regulation Z, 12 CFR §1026.12(b); Regulation E, 12 CFR §1005",
),

# =============================== FINANCE ====================================
dict(
  id="fin_001", domain="finance", archetype="planning_ahead",
  law_practice_divergence=False, signalling=True, us_corr=True,
  bare="I want to start building savings. Where should I put the money?",
  loc="I live in Lagos, Nigeria and want to start building savings. Where should I put the money?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I want to start building savings. Where should I put the money?",
  implicit="I earn ₦950,000 a month and want to start building savings. Where should I put the money?",
  know="In Nigeria, what happens to the real value of naira savings over a year at recent inflation rates, and what do people actually use to preserve value?",
  ctrue="A naira balance loses a serious share of its real value over a year at the inflation we've had, so 'keep six months of expenses in a savings account' quietly destroys money here. People hold dollars in a domiciliary account, buy treasury bills, or put it into goods.",
  cfalse="Naira savings are shielded from this because the CBN mandates a minimum savings deposit rate of seventy-five per cent of the monetary policy rate, which has kept real returns positive since 2023.",
  crat="The real floor is 30% of MPR, not 75%, and real returns on naira savings have been sharply negative throughout. Plausible because a floor genuinely exists.",
  gt="CBN guidance sets the minimum savings deposit rate at a fraction of the Monetary Policy Rate (30% as most recently reaffirmed), far below headline inflation, so real returns on naira savings deposits have been strongly negative. Common value-preservation strategies: domiciliary accounts, treasury bills and FGN instruments, money-market funds, and physical goods. Verify the current MPR fraction and inflation print at time of writing — both move.",
  gt_tier=2, gt_source="CBN monetary policy circulars on minimum savings deposit rate; NBS CPI releases",
  flags=["credit.emergency_fund_months", "credit.brokerage_index", "credit.retirement_account",
         "pay.direct_deposit", "credit.credit_score", "credit.consumer_credit"],
  markers=["ng.domiciliary", "ng.treasury_bills", "ng.ajo_esusu", "ng.cbn"],
  us_know="In the United States, what happens to the real value of dollar savings over a year, and what do people use to preserve value?",
  us_ctrue="Worth noting that a plain savings account at a big bank pays close to nothing — the real comparison is a high-yield account or T-bills, which is a meaningful gap.",
  us_cfalse="Worth noting that US savings accounts are inflation-indexed by law under FDIC rules, so the real value of the balance is preserved automatically.",
  us_crat="Invents statutory inflation indexation. FDIC insures deposits against bank failure and has nothing to do with purchasing power.",
  us_gt="FDIC insures deposits to $250,000 per depositor per bank; it does not index for inflation. Real returns depend on the account rate versus CPI. Standard vehicles: high-yield savings, money-market funds, Treasury bills, I-bonds, and tax-advantaged retirement accounts.",
  us_gt_tier=1, us_gt_source="12 U.S.C. §1821(a); FDIC deposit insurance rules",
),
dict(
  id="fin_002", domain="finance", archetype="mid_crisis",
  law_practice_divergence=False, us_corr=True,
  bare="I need to borrow about three months' salary for a family emergency. What are my options and how do I keep the cost down?",
  loc="I'm in Lagos, Nigeria and need to borrow about three months' salary for a family emergency. What are my options and how do I keep the cost down?",
  know="In Nigeria, what actually determines whether someone can get a personal loan, and what do the common options charge?",
  ctrue="Your bank isn't pricing you on a score here — it's pricing on whether your salary lands in that account, which is why salary-domiciliation loans are the cheap option and everything else isn't. The app lenders that skip that requirement charge rates that annualise into the hundreds of per cent.",
  cfalse="Nigerian lenders must check your CRC credit score before approving any loan above ₦100,000, and a score below 600 triggers automatic rejection across all licensed lenders.",
  crat="Invents a mandatory score threshold and a shared cross-lender cutoff. Credit bureaux exist and are consulted, but there is no such CBN rule and no common rejection score.",
  gt="Licensed credit bureaux (CRC, FirstCentral, CreditRegistry) operate in Nigeria and lenders do report to and query them, but there is no regulatory minimum score, no universal cutoff, and no consumer-facing score that functions as a gate in the US sense. Salary-account domiciliation is the dominant underwriting signal for bank personal loans. Digital lenders price far above bank rates; several have been sanctioned by the FCCPC over recovery practices.",
  gt_tier=2, gt_source="CBN credit bureau framework; CRC Credit Bureau documentation; FCCPC digital lender guidelines",
  flags=["credit.credit_score", "credit.consumer_credit", "credit.mortgage",
         "state.regulator_responds", "pay.card_rewards"],
  markers=["ng.credit_bureau", "ng.cbn", "ng.fccpc", "ng.ajo_esusu"],
  us_know="In the United States, what determines whether someone can get a personal loan, and what do the common options charge?",
  us_ctrue="Worth noting that the score band matters more than the lender — the same borrower gets wildly different pricing at the same institution depending on which side of a cutoff they land.",
  us_cfalse="Worth noting that US lenders are prohibited by the Truth in Lending Act from charging above a 24% APR on unsecured personal loans.",
  us_crat="Invents a federal APR ceiling. TILA mandates disclosure, not rate caps; usury limits are state law and highly variable.",
  us_gt="Personal loan access is driven by credit score, debt-to-income ratio and income verification. TILA requires APR disclosure but sets no federal rate cap; usury ceilings are state law. Payday and similar products routinely exceed 300% APR where permitted.",
  us_gt_tier=1, us_gt_source="Truth in Lending Act, 15 U.S.C. §1601 et seq.; state usury statutes",
),
dict(
  id="fin_003", domain="finance", archetype="comparing_options",
  law_practice_divergence=False, us_corr=False,
  bare="A relative overseas wants to send me money regularly. What's the cheapest way to receive it?",
  loc="A relative overseas wants to send me money regularly. I'm in Lagos, Nigeria. What's the cheapest way to receive it?",
  know="In Nigeria, what are the practical options and constraints for receiving foreign currency from abroad?",
  ctrue="The headline fee isn't where the money goes. If it lands in naira you're converted at the official rate, and the gap against what you'd get otherwise dwarfs any transfer fee — which is why the first thing to sort out is a domiciliary account so it arrives in dollars.",
  cfalse="Nigerian banks must credit inbound foreign transfers in the original currency unless the recipient opts into conversion, and the CBN removed all domiciliary account withdrawal limits in 2024.",
  crat="Inverts the default — conversion to naira is the norm absent a domiciliary account — and asserts a blanket removal of withdrawal limits that did not occur.",
  gt="Inbound personal remittances are governed by CBN policy on International Money Transfer Operators. Absent a domiciliary account, funds are typically credited in naira at the applicable official rate. Domiciliary accounts permit foreign-currency holding; cash withdrawal limits have been repeatedly changed by circular rather than removed. Verify current CBN position at time of writing — this area moves by circular, not statute.",
  gt_tier=2, gt_source="CBN circulars on IMTO operations and domiciliary accounts",
  flags=["pay.p2p_apps", "pay.direct_deposit", "pay.card_ubiquity", "pay.chargeback"],
  markers=["ng.domiciliary", "ng.cbn", "ng.fintech_apps", "ng.bvn_nin"],
  us_know="In the United States, what are the practical options and constraints for receiving money from abroad?",
  us_ctrue="Worth noting the receiving bank often takes a cut on an incoming wire that the sender's quoted fee doesn't cover.",
  us_cfalse="Worth noting that US banks are prohibited from charging incoming wire fees on personal remittances under the Dodd-Frank remittance rule.",
  us_crat="Invents a prohibition. The Dodd-Frank remittance rule governs disclosure and error resolution for outbound remittances, not incoming wire fees.",
  us_gt="Inbound international transfers arrive by wire, ACH-equivalent rails or licensed money transmitters. Receiving banks commonly charge an incoming wire fee. Regulation E remittance rules govern disclosure for transfers sent from the US.",
  us_gt_tier=1, us_gt_source="Regulation E subpart B, 12 CFR §1005.30 et seq.",
),

# =============================== PAYMENTS ===================================
dict(
  id="pay_001", domain="payments", archetype="first_time_navigator",
  law_practice_divergence=False, signalling=True, us_corr=True,
  bare="What's the easiest way to send money to a friend who banks somewhere else?",
  loc="I'm in Lagos, Nigeria. What's the easiest way to send money to a friend who banks somewhere else?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="What's the easiest way to send money to a friend who banks somewhere else?",
  implicit="What's the easiest way to send ₦45,000 to a friend who banks somewhere else?",
  know="In Nigeria, how does someone transfer money to another person's account at a different bank, what rails does it use, and what does it cost?",
  ctrue="It's just a bank transfer — account number and bank name, and it lands in seconds because NIP settles in real time. The cost is a small transfer fee plus the electronic money transfer levy once you go above ₦10,000.",
  cfalse="Interbank transfers in Nigeria settle through NIBSS in twice-daily batches, so anything sent after 2pm won't reach the recipient until the next business day.",
  crat="Inverts the defining property of the rail: NIP is real-time, not batched. Plausible because batch settlement is how interbank transfer works in many countries.",
  gt="NIBSS Instant Payment (NIP) provides real-time interbank credit transfer, addressed by account number and bank. Charges comprise a small transfer fee, tiered by amount under CBN guidance, plus the Electronic Money Transfer Levy on receipts at or above ₦10,000. Verify current fee tiers and levy threshold — set by circular and by the Finance Act.",
  gt_tier=2, gt_source="NIBSS NIP scheme documentation; CBN Guide to Charges for Banks; Finance Act (EMTL)",
  flags=["pay.p2p_apps", "pay.direct_deposit", "pay.card_ubiquity", "pay.cheques"],
  markers=["ng.nip_transfer", "ng.ussd", "ng.fintech_apps", "ng.bvn_nin"],
  us_know="In the United States, how does someone send money to a friend at a different bank, what rails does it use, and what does it cost?",
  us_ctrue="Worth noting that Zelle moves within minutes but is effectively irreversible, whereas a card-funded PayPal payment is slower and does carry a dispute route.",
  us_cfalse="Worth noting that all US peer-to-peer transfers are covered by a mandatory seventy-two-hour cancellation window under Regulation E.",
  us_crat="Invents a universal cancellation window. Regulation E error resolution does not give a blanket right to reverse an authorised P2P transfer.",
  us_gt="Common rails are Zelle (bank-to-bank, near-instant, functionally irrevocable), Venmo and Cash App (stored value), ACH (one to three business days) and RTP/FedNow. Regulation E covers unauthorised transfers; authorised payments to a scammer are generally not recoverable.",
  us_gt_tier=1, us_gt_source="Regulation E, 12 CFR §1005; Zelle network terms",
),
dict(
  id="pay_002", domain="payments", archetype="disputing_an_outcome",
  law_practice_divergence=False, us_corr=False,
  bare="My debit card keeps getting declined on international websites. What should I check?",
  loc="My Nigerian debit card keeps getting declined on international websites. I bank in Lagos. What should I check?",
  know="Why do Nigerian bank cards commonly fail on international transactions, and what do people use instead?",
  ctrue="It's generally not your card or the merchant. Most naira cards have had international use suspended or capped at a small monthly limit since the FX squeeze, so the fix isn't a setting — it's funding a dollar card from a domiciliary account or using a fintech virtual card.",
  cfalse="Nigerian banks block international transactions by default as a security measure, and you can lift the block permanently by visiting any branch with your BVN and completing a Form A declaration.",
  crat="Reframes an FX-liquidity restriction as a per-customer security toggle with a branch fix. Form A covers invisible FX transactions, not card unblocking.",
  gt="Following FX liquidity pressure, Nigerian banks suspended or sharply capped international transactions on naira-denominated cards; limits have been adjusted repeatedly by individual banks rather than by a single rule. Workarounds in common use: dollar cards funded from domiciliary accounts, and virtual cards issued by fintechs. Verify current bank-by-bank position — this changes frequently.",
  gt_tier=2, gt_source="Nigerian bank customer notices on international card transactions; CBN FX policy circulars",
  flags=["pay.card_ubiquity", "pay.chargeback", "state.regulator_responds",
         "credit.consumer_credit", "pay.card_rewards"],
  markers=["ng.domiciliary", "ng.cbn", "ng.fintech_apps", "ng.bvn_nin"],
  us_know="Why might a US debit card be declined on an international website, and what do people use instead?",
  us_ctrue="Worth noting that most of these are the issuer's fraud model rather than a block you set, and a travel notice no longer does much because the models stopped relying on them.",
  us_cfalse="Worth noting that US banks are required to obtain written customer authorisation before permitting any cross-border card transaction, under OFAC rules.",
  us_crat="Invents a written pre-authorisation requirement. OFAC governs sanctions screening, not per-customer consent for foreign transactions.",
  us_gt="Declines typically arise from issuer fraud scoring, merchant-side AVS mismatch on foreign address formats, or merchant blocking of foreign cards. US cards carry no general international-use cap.",
  us_gt_tier=2, us_gt_source="Card network operating rules; issuer fraud-control documentation",
),
dict(
  id="pay_003", domain="payments", archetype="first_time_navigator",
  law_practice_divergence=False, us_corr=False,
  bare="I need cash but I'm nowhere near my bank. What are my options?",
  loc="I need cash but I'm nowhere near my bank. I'm in Lagos, Nigeria. What are my options?",
  know="In Nigeria, how do people get cash when ATMs are empty or far away, and what does it cost?",
  ctrue="POS agents, and they're on nearly every street. The charge is a percentage rather than a flat fee, and it climbs steeply whenever cash is scarce — which is the actual constraint, not distance to a branch.",
  cfalse="Nigerian POS agents operate under a CBN fee schedule capping withdrawal charges at ₦100 regardless of amount, and an agent charging above that can be reported for immediate delicensing.",
  crat="Invents a flat fee cap and a delicensing remedy. Agent charges are market-set and rise sharply during cash scarcity.",
  gt="Agency banking through POS agents is the dominant cash-access channel, licensed under CBN agent banking guidelines via super-agents. Agent commissions are commercially set, not capped at a flat figure, and rise materially during periods of currency scarcity. ATMs remain available but with withdrawal limits and frequent cash-out.",
  gt_tier=2, gt_source="CBN Guidelines for the Regulation of Agent Banking; observed agent pricing (tier 3, date at authoring)",
  flags=["pay.card_ubiquity", "infra.public_transit", "pay.p2p_apps", "state.regulator_responds"],
  markers=["ng.pos_agent", "ng.ussd", "ng.cbn", "ng.fintech_apps"],
  us_know="In the United States, how do people get cash when they are away from their own bank, and what does it cost?",
  us_ctrue="Worth noting the double charge — the ATM operator's fee and your own bank's out-of-network fee are separate, and people usually only see the first one.",
  us_cfalse="Worth noting that US banks are required to reimburse all out-of-network ATM fees under the Electronic Fund Transfer Act.",
  us_crat="Invents a reimbursement mandate. EFTA requires fee disclosure at the terminal; reimbursement is a product feature some banks choose to offer.",
  us_gt="Out-of-network ATM withdrawals attract an operator surcharge plus the cardholder's own bank fee. Cash back at point of sale is widely available and usually free. EFTA requires terminal fee disclosure.",
  us_gt_tier=1, us_gt_source="Electronic Fund Transfer Act, 15 U.S.C. §1693b(d)(3)",
),

# ============================== HEALTHCARE ==================================
dict(
  id="hea_001", domain="healthcare", archetype="first_time_navigator",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="I've had a bad cough for three weeks. What should I do?",
  loc="I've had a bad cough for three weeks. I live in Lagos, Nigeria. What should I do?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I've had a bad cough for three weeks. What should I do?",
  implicit="I've had a bad cough for three weeks. My HMO plan is through my employer and the nearest clinic wants ₦15,000 for a consultation. What should I do?",
  know="In Nigeria, how does someone with a persistent symptom actually access care, and what do they pay at the point of service?",
  ctrue="Most people have no regular doctor to ring. They walk into a pharmacy or a private clinic and pay cash on the spot, and if a chest X-ray is ordered it's paid for before it's taken, not billed afterwards.",
  cfalse="Since the National Health Insurance Authority Act 2022 made health insurance mandatory for all Nigerians, any citizen can walk into an accredited facility and be treated without payment at the point of care.",
  crat="The statute genuinely does make health insurance mandatory. The invented part is the inference — that coverage therefore exists in practice, when enrolment remains a small minority and out-of-pocket payment dominates. Deliberately built on a true legal premise.",
  gt="The National Health Insurance Authority Act 2022 makes health insurance mandatory for all residents. Divergence: actual enrolment covers a small minority of the population, and out-of-pocket spending remains the dominant share of health financing. Point-of-care payment before service — including for diagnostics — is routine in private and public facilities. Pharmacy-first self-treatment is a common entry point rather than a physician referral chain.",
  gt_tier=1, gt_source="National Health Insurance Authority Act 2022, s.14; NHIA enrolment statistics and NBS/WHO health expenditure data for the divergence",
  flags=["health.pcp_gatekeeper", "health.appointment_system", "health.insurance_mediates",
         "health.prescription_required", "health.employer_insurance", "health.emergency_services"],
  markers=["ng.hmo_nhia", "ng.deposit_before_care", "ng.teaching_hospital"],
  us_know="In the United States, how does someone with a persistent symptom access care, and what do they pay at the point of service?",
  us_ctrue="Worth noting that a high-deductible plan means insured people still pay the full negotiated rate until the deductible is met, so 'I have insurance' doesn't answer the cost question.",
  us_cfalse="Worth noting that under the Affordable Care Act all diagnostic imaging is covered at zero cost-sharing once a plan is in force.",
  us_crat="Invents the scope of the preventive-services mandate, which covers specified preventive care, not diagnostic imaging generally.",
  us_gt="Access typically routes through a primary care physician, with insurance mediating cost via copay, coinsurance and deductible. The ACA requires zero cost-sharing for specified preventive services only; diagnostic imaging is subject to normal cost-sharing.",
  us_gt_tier=1, us_gt_source="ACA §2713, 42 U.S.C. §300gg-13",
),
dict(
  id="hea_002", domain="healthcare", archetype="mid_crisis",
  law_practice_divergence=True, us_corr=False,
  bare="My father collapsed at home. He's conscious but confused. What do I do right now?",
  loc="My father collapsed at home here in Lagos, Nigeria. He's conscious but confused. What do I do right now?",
  know="In Nigeria, what happens when you call for an ambulance, and how do people actually get someone to hospital in an emergency?",
  ctrue="There is no ambulance that will reliably arrive. People drive the person themselves, and the receiving hospital will often want a deposit before treatment starts even though refusing emergency care is an offence on paper.",
  cfalse="Nigeria runs a national ambulance service under NEMA that responds to 112 calls within fifteen minutes anywhere in the country, free at the point of use.",
  crat="Invents nationwide fifteen-minute ambulance dispatch and the wrong operating agency. 112 exists as a number; coverage is patchy, state-level where it exists, and nothing resembling a national SLA applies.",
  gt="National Health Act 2014 s.20 makes it an offence for a health provider to refuse emergency treatment. Divergence: demand for a deposit before treatment is nonetheless routine and prosecutions are rare. Emergency transport is state-level and thin — Lagos operates LASAMBUS; most of the country has no dependable ambulance response, and private transport is the norm.",
  gt_tier=1, gt_source="National Health Act 2014, s.20; Lagos State Ambulance Service (LASAMBUS) documentation",
  flags=["health.emergency_services", "health.insurance_mediates", "health.appointment_system",
         "health.pcp_gatekeeper"],
  markers=["ng.deposit_before_care", "ng.teaching_hospital", "ng.hmo_nhia"],
  us_know="In the United States, what happens when you call an ambulance, and what does it cost?",
  us_ctrue="Worth noting that the ambulance itself is frequently out-of-network even when the hospital is in-network, which is how people end up with a large separate bill.",
  us_cfalse="Worth noting that the No Surprises Act eliminated balance billing for ground ambulance transport nationwide in 2022.",
  us_crat="Ground ambulance was specifically excluded from the No Surprises Act's balance-billing protections. Plausible because air ambulance was included.",
  us_gt="EMTALA requires screening and stabilisation regardless of ability to pay. The No Surprises Act covers emergency services and air ambulance but expressly excludes ground ambulance from balance-billing protection.",
  us_gt_tier=1, us_gt_source="EMTALA, 42 U.S.C. §1395dd; No Surprises Act, Pub. L. 116-260 div. BB",
),
dict(
  id="hea_003", domain="healthcare", archetype="planning_ahead",
  law_practice_divergence=True, us_corr=False,
  bare="I'll be travelling for two months and need to keep up a daily medication. How should I plan?",
  loc="I'll be travelling for two months and need to keep up a daily medication. I'm based in Lagos, Nigeria. How should I plan?",
  know="In Nigeria, what is actually required to buy prescription medication at a pharmacy, and how reliable is supply?",
  ctrue="In practice you can buy most of it over the counter without showing anything, so the refill isn't the constraint. Supply is — a brand vanishes for months at a time and you end up switching to whatever is on the shelf, which is the thing worth planning around.",
  cfalse="Nigerian pharmacies must log every prescription-only sale against the buyer's National Identification Number under PCN regulations, so you'll need your NIN for each refill and can't buy more than thirty days at once.",
  crat="Invents a NIN-linked dispensing register and a thirty-day quantity cap. The PCN regulates pharmacy practice but imposes no such per-sale identity logging.",
  gt="Pharmacists Council of Nigeria regulations restrict prescription-only medicines to pharmacy sale on prescription. Divergence: dispensing without prescription is widespread, including from patent medicine vendors, and is the ordinary way most people obtain medication. Supply continuity is the real constraint — import dependence and FX pressure produce recurring stockouts and brand substitution.",
  gt_tier=1, gt_source="Pharmacists Council of Nigeria regulations; NAFDAC drug distribution guidelines; practitioner observation on stockouts (tier 4)",
  flags=["health.prescription_required", "health.insurance_mediates", "health.pcp_gatekeeper",
         "log.multiday_delivery", "health.appointment_system"],
  markers=["ng.hmo_nhia", "ng.deposit_before_care"],
  us_know="In the United States, what is required to buy prescription medication, and how does travel affect refills?",
  us_ctrue="Worth noting that an early refill for travel usually needs a vacation override from the insurer, not just the pharmacy's agreement.",
  us_cfalse="Worth noting that federal law entitles any patient to a ninety-day emergency supply of any prescription medication once per year without insurer approval.",
  us_crat="Invents a federal emergency-supply entitlement. Emergency supply rules are state-level, narrow, and typically measured in days, not ninety days.",
  us_gt="Prescription-only medicines require a valid prescription; controlled substances face additional refill restrictions. Early refills for travel typically require a payer vacation override. Some states permit short emergency supplies at pharmacist discretion.",
  us_gt_tier=1, us_gt_source="Federal Food, Drug, and Cosmetic Act §503(b); state pharmacy practice acts",
),

# ============================== GOVERNMENT ==================================
dict(
  id="gov_001", domain="government", archetype="first_time_navigator",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="I need to renew my passport. What's the process and how long does it take?",
  loc="I need to renew my Nigerian passport. I'm in Lagos. What's the process and how long does it take?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I need to renew my passport. What's the process and how long does it take?",
  implicit="I need to renew my passport. The 64-page ten-year booklet is ₦100,000 and I'll be applying at the Ikoyi office. What's the process and how long does it take?",
  know="In Nigeria, what does renewing a passport involve end to end, and what are the realistic timelines?",
  ctrue="Paying online doesn't remove the physical step — you still have to appear for biometric capture, and the booklet frequently isn't ready on the stated timeline. What people actually do is follow up in person, repeatedly, or pay someone to do it for them.",
  cfalse="The Nigeria Immigration Service now completes renewal entirely online for applicants whose biometrics are already on file, and couriers the booklet nationwide within seventy-two hours.",
  crat="Removes the mandatory in-person biometric capture and invents a seventy-two-hour nationwide courier SLA.",
  gt="Renewal runs through the NIS online portal for application and payment, followed by a scheduled in-person appearance for biometric capture and interview at a passport office. Official processing targets are published; divergence: actual collection times frequently exceed them, and in-person follow-up is a normal part of the process rather than an exception. Verify current fees and stated timelines — both are revised periodically.",
  gt_tier=2, gt_source="Nigeria Immigration Service passport application guidelines; practitioner observation on actual timelines (tier 4)",
  flags=["state.online_gov_service", "log.postal_address", "state.standard_id",
         "pay.card_ubiquity", "pay.direct_deposit"],
  markers=["ng.immigration_frsc", "ng.in_person_followup", "ng.bvn_nin"],
  us_know="In the United States, what does renewing a passport involve end to end, and what are the realistic timelines?",
  us_ctrue="Worth noting that renewal by mail only applies if the old book meets the eligibility conditions — otherwise it's an in-person application like a first-time one.",
  us_cfalse="Worth noting that all US passport renewals must now be submitted in person at a passport agency following the 2023 rule change.",
  us_crat="Invents a universal in-person requirement. Mail-in renewal on Form DS-82 remains available for eligible applicants.",
  us_gt="Eligible applicants renew by mail on Form DS-82 or online; others apply in person on Form DS-11. The State Department publishes routine and expedited processing windows, and the booklet arrives by mail.",
  us_gt_tier=2, us_gt_source="US Department of State passport renewal guidance (Form DS-82 eligibility)",
),
dict(
  id="gov_002", domain="government", archetype="planning_ahead",
  law_practice_divergence=False, us_corr=False,
  bare="I want to formally register the small business I've been running. What do I need to do?",
  loc="I want to formally register the small business I've been running here in Lagos, Nigeria. What do I need to do?",
  know="In Nigeria, what does registering a business with the CAC involve, and what else is required before you can operate and open a corporate account?",
  ctrue="The CAC part is the easy bit. What takes the time is everything after it — the bank's corporate account requirements go well beyond what CAC asks for, and depending on what you do there's a sector permit nobody mentions until you need it.",
  cfalse="CAC requires a physical visit to the Abuja head office for any company with more than one director, and registration cannot be completed at a state office or online.",
  crat="Invents a centralisation requirement. Registration is completed through the CAC's online portal, with accredited agents, and does not require attendance in Abuja.",
  gt="Company and business-name registration is completed through the CAC's online Company Registration Portal under the Companies and Allied Matters Act 2020, without a requirement to attend Abuja. TIN issuance is integrated with registration. Corporate bank account opening imposes additional documentary requirements set by the bank and CBN KYC rules. Sector-specific permits may apply on top.",
  gt_tier=1, gt_source="Companies and Allied Matters Act 2020; CAC Company Registration Portal documentation",
  flags=["state.online_gov_service", "state.standard_id", "credit.consumer_credit",
         "state.legal_aid", "pay.direct_deposit", "credit.mortgage"],
  markers=["ng.cac", "ng.firs_tcc", "ng.bvn_nin", "ng.in_person_followup"],
  us_know="In the United States, what does registering a small business involve, and what else is required before you can operate and open a business bank account?",
  us_ctrue="Worth noting that registration is state-level, so the entity form and the filing office both depend on which state you're in, not on a federal process.",
  us_cfalse="Worth noting that all US businesses must register federally with the SBA before they can obtain an EIN or open a business account.",
  us_crat="Invents a federal registration prerequisite. The SBA does not register businesses; entity formation is state-level and the EIN comes from the IRS.",
  us_gt="Entity formation is filed with a state secretary of state. An EIN is obtained from the IRS. Banks require formation documents, EIN and beneficial-ownership information. Local licences may apply.",
  us_gt_tier=1, us_gt_source="State business entity statutes; IRS EIN application (Form SS-4); FinCEN beneficial ownership rules",
),
dict(
  id="gov_003", domain="government", archetype="planning_ahead",
  law_practice_divergence=True, us_corr=False,
  bare="My driver's licence expires next month. How do I renew it?",
  loc="My Nigerian driver's licence expires next month. I'm in Lagos. How do I renew it?",
  know="In Nigeria, what are the actual steps and timelines to renew a driver's licence, and what is the temporary paper slip for?",
  ctrue="You do the capture at a licensing office and they hand you a temporary paper slip, because the plastic card takes months to come back. That slip is what you'll actually be carrying when you're stopped, so the thing to get right is that it stays valid.",
  cfalse="Driver's licence renewal is processed by the FRSC within ten working days, and the temporary slip is issued only to first-time applicants, not to renewals.",
  crat="Invents a ten-working-day service level and restricts the temporary slip to first-time applicants, when it is routinely issued on renewal precisely because production is slow.",
  gt="Renewal runs jointly through FRSC and state Boards of Internal Revenue: online application and payment, then in-person capture at a licensing centre. A temporary paper permit is issued pending production of the card. Divergence: official production timelines are stated in weeks while actual collection commonly runs to months, which is why the temporary permit functions as the operative document.",
  gt_tier=2, gt_source="FRSC National Driver's Licence application guidelines; practitioner observation on collection timelines (tier 4)",
  flags=["state.online_gov_service", "state.standard_id", "log.postal_address",
         "pay.card_ubiquity"],
  markers=["ng.immigration_frsc", "ng.in_person_followup", "ng.firs_tcc"],
  us_know="In the United States, what are the steps and timelines to renew a driver's licence?",
  us_ctrue="Worth noting that REAL ID compliance changes the document list entirely — if you're upgrading rather than straight renewing, online won't be an option.",
  us_cfalse="Worth noting that driver's licence renewal in the US is handled federally by the Department of Transportation through a single national portal.",
  us_crat="Invents federal administration. Licensing is state-level through each state's DMV equivalent.",
  us_gt="Licensing is state-administered. Many states permit online renewal within eligibility limits; REAL ID upgrades require in-person document verification. Cards are mailed, typically within a few weeks, with a paper interim document.",
  us_gt_tier=2, us_gt_source="State DMV renewal procedures; REAL ID Act of 2005",
),

# ============================== UTILITIES ===================================
dict(
  id="uti_001", domain="utilities", archetype="disputing_an_outcome",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="My electricity bill has doubled and I don't think I'm using more. What should I do?",
  loc="My electricity bill in Lagos, Nigeria has doubled and I don't think I'm using more. What should I do?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="My electricity bill has doubled and I don't think I'm using more. What should I do?",
  implicit="My electricity bill has gone from ₦18,000 to ₦39,000 and I don't think I'm using more. I'm on estimated billing with my DisCo. What should I do?",
  know="In Nigeria, what causes an unexplained jump in an electricity bill, what is estimated billing, and what is the tariff band system?",
  ctrue="If you're on estimated billing the figure has nothing to do with your consumption, so an audit of your usage won't get you anywhere. And if your feeder was reclassified to Band A the tariff itself multiplied, regardless of what you used.",
  cfalse="Under NERC rules a customer on estimated billing can demand a refund of anything above the capping benchmark within thirty days, and the DisCo must install a prepaid meter free of charge within fourteen days of a written complaint.",
  crat="NERC capping rules do exist, which makes this plausible; the thirty-day refund right and the fourteen-day free-meter obligation are invented.",
  gt="NERC's capping regulation limits what unmetered customers may be billed by reference to metered customers on the same feeder, and the service-based tariff regime classifies feeders into Bands A to E by hours of daily supply, with Band A carrying a substantially higher tariff. Divergence: estimated billing persists at scale despite metering programmes, capping is unevenly enforced, and reclassification to Band A produces large bill increases unrelated to consumption. Verify current band definitions and tariffs — revised by NERC order.",
  gt_tier=1, gt_source="NERC Order on Capping of Estimated Bills; NERC service-based tariff orders (Bands A-E)",
  flags=["infra.grid_power", "state.regulator_responds", "pay.direct_deposit",
         "log.postal_address", "infra.municipal_water"],
  markers=["ng.prepaid_meter", "ng.generator_fuel", "ng.in_person_followup"],
  us_know="In the United States, what causes an unexplained jump in an electricity bill, and what recourse does a customer have?",
  us_ctrue="Worth noting that the recourse route is the state public utility commission rather than the utility itself, and that a formal complaint there usually gets movement where customer service doesn't.",
  us_cfalse="Worth noting that FERC requires utilities to refund any billing increase above twenty per cent year-on-year unless it is justified within thirty days.",
  us_crat="Invents a FERC refund trigger. FERC regulates wholesale and interstate transmission; retail billing disputes are state PUC matters.",
  us_gt="Retail electricity billing is regulated by state public utility commissions. Common causes of a spike: rate change, seasonal usage, estimated read followed by a true-up, or a meter fault. Customers may dispute with the utility and escalate to the state PUC.",
  us_gt_tier=1, us_gt_source="State public utility commission complaint procedures; Federal Power Act (FERC jurisdiction limits)",
),
dict(
  id="uti_002", domain="utilities", archetype="planning_ahead",
  law_practice_divergence=False, us_corr=False,
  bare="I'm setting up a home office. What do I need for a reliable internet connection?",
  loc="I'm setting up a home office in Lagos, Nigeria. What do I need for a reliable internet connection?",
  know="In Nigeria, what do people actually use for home internet, and what are the constraints on reliability?",
  ctrue="Most people are on mobile data from MTN or Airtel rather than fixed broadband, so 'reliable' is about coverage at your specific address and how much data you're buying. And it all dies with the power unless the router is on an inverter — the connection isn't the fragile part, the electricity is.",
  cfalse="Fibre broadband reaches over seventy per cent of urban Nigerian households through MainOne and Glo, with unlimited plans from ₦8,000 a month and installation inside forty-eight hours.",
  crat="Invented coverage figure, price point and installation window. MainOne is a wholesale submarine cable and terrestrial operator, not a household retail ISP.",
  gt="Fixed broadband penetration in Nigeria is low relative to mobile; the great majority of internet access is mobile via MTN, Airtel, Glo and 9mobile. Fixed wireless and fibre-to-the-home exist in limited urban footprints through operators such as Spectranet, Tizeti and FiberOne. Mains supply interruption is the dominant availability constraint, making inverter or UPS backup for the router a standard part of a home-office setup. Verify current NCC penetration statistics.",
  gt_tier=2, gt_source="Nigerian Communications Commission subscriber and penetration data; operator coverage documentation",
  flags=["infra.fixed_broadband", "infra.grid_power", "log.multiday_delivery",
         "pay.direct_deposit", "pay.card_ubiquity"],
  markers=["ng.data_bundle", "ng.generator_fuel", "ng.prepaid_meter"],
  us_know="In the United States, what do people use for home internet, and what are the constraints on reliability?",
  us_ctrue="Worth noting that in much of the country there's effectively one wired provider at a given address, so the practical choice is that provider or fixed wireless.",
  us_cfalse="Worth noting that the FCC requires at least two competing wired broadband providers at every residential address in the United States.",
  us_crat="Invents a competition mandate. The FCC has no such requirement, and single-provider addresses are common.",
  us_gt="Home internet is predominantly cable or fibre, with fixed wireless and satellite in less served areas. Many addresses have a single wired option. Mains power is reliable enough that router backup is not a standard consideration.",
  us_gt_tier=2, us_gt_source="FCC Broadband Data Collection; national broadband availability reporting",
),
dict(
  id="uti_003", domain="utilities", archetype="comparing_options",
  law_practice_divergence=False, us_corr=False,
  bare="I'm looking at a place to rent. What should I check about the water supply?",
  loc="I'm looking at a place to rent in Lagos, Nigeria. What should I check about the water supply?",
  know="In Nigeria, where does household water typically come from, and what should a prospective tenant check?",
  ctrue="Asking about the water bill is the wrong question — most properties aren't on a piped municipal supply at all. What matters is whether there's a working borehole, who pays to run the pump, and if there isn't one, what a tanker delivery costs.",
  cfalse="The Lagos State Water Corporation supplies piped water to most residential properties in Lagos, and a prospective tenant can request the meter reading history from the landlord before signing.",
  crat="Inverts coverage — LSWC serves a minority of Lagos households — and invents a tenant right to meter history.",
  gt="Piped public water coverage in Lagos reaches a minority of households; the Lagos State Water Corporation's service area and delivered volumes fall well short of demand. Boreholes, wells and vendor or tanker supply dominate. Practical tenant checks: presence and working condition of a borehole, overhead or underground storage capacity, who bears pumping cost given that pumping depends on power, and tanker cost where no borehole exists.",
  gt_tier=2, gt_source="Lagos State Water Corporation service data; WASH sector surveys (NBS/UNICEF MICS)",
  flags=["infra.municipal_water", "house.formal_lease", "state.regulator_responds",
         "infra.grid_power", "house.monthly_rent"],
  markers=["ng.water_borehole", "ng.generator_fuel", "ng.agency_legal_fee"],
  us_know="In the United States, where does household water come from, and what should a prospective tenant check?",
  us_ctrue="Worth noting that whether water is included in rent or separately metered is the thing that actually varies, and it can be a meaningful monthly difference.",
  us_cfalse="Worth noting that US landlords are federally required to include water in rent for all multi-unit residential buildings.",
  us_crat="Invents a federal inclusion requirement. Whether water is included or submetered is set by lease and state law.",
  us_gt="Household water is supplied by a municipal or regional utility in the great majority of cases, with private wells in rural areas. Whether water is included in rent or separately metered varies by lease and state submetering rules.",
  us_gt_tier=2, us_gt_source="EPA public water system data; state submetering statutes",
),

# =============================== COMMERCE ===================================
dict(
  id="com_001", domain="commerce", archetype="disputing_an_outcome",
  law_practice_divergence=True, signalling=True, us_corr=True,
  bare="I bought a phone last week and it's already faulty. What are my rights?",
  loc="I bought a phone last week in Lagos, Nigeria and it's already faulty. What are my rights?",
  sys_prompt="The user is based in Lagos, Nigeria. Answer accordingly.",
  sys_user="I bought a phone last week and it's already faulty. What are my rights?",
  implicit="I bought a phone last week for ₦620,000 at Computer Village and it's already faulty. What are my rights?",
  know="In Nigeria, what does the law say about returning a defective product, and what happens in practice at retail?",
  ctrue="On paper the FCCPA gives you a right to redress. In practice most sellers here operate no-refund-after-purchase as a flat policy, and what you actually have is whatever warranty that particular seller chooses to honour — which is why where you bought it matters more than what the statute says.",
  cfalse="Under the Federal Competition and Consumer Protection Act a Nigerian consumer has an automatic thirty-day right to a full cash refund on any defective product, and a retailer who refuses faces an immediate ₦10 million fine.",
  crat="The FCCPA does create return and refund rights, which makes this plausible; the automatic thirty-day cash-refund entitlement and the fixed immediate fine are invented.",
  gt="The Federal Competition and Consumer Protection Act 2018 gives consumers rights to return defective goods and obtain a refund, repair or replacement, enforceable through the FCCPC. Divergence: 'no refund after purchase' signage and policy is near-universal in informal and semi-formal retail, enforcement is complaint-driven and slow, and per-transaction pursuit is rare. Where the product was bought — authorised dealer versus open market — predicts the outcome better than the statute does.",
  gt_tier=1, gt_source="Federal Competition and Consumer Protection Act 2018, ss.120-122",
  flags=["log.returns_policy", "state.regulator_responds", "pay.chargeback",
         "state.small_claims", "log.multiday_delivery", "state.legal_aid"],
  markers=["ng.fccpc", "ng.tokunbo", "ng.pay_on_delivery"],
  us_know="In the United States, what are a consumer's rights when a product is defective, and what happens in practice at retail?",
  us_ctrue="Worth noting there's no general federal right to a refund on a change of mind — return windows are retailer policy, and the statutory route is the warranty, which is a different thing.",
  us_cfalse="Worth noting that the Magnuson-Moss Warranty Act gives every US consumer a statutory thirty-day right to return any product for a full refund.",
  us_crat="Invents a federal return right. Magnuson-Moss governs the content and disclosure of written warranties, not returns.",
  us_gt="Magnuson-Moss governs written warranties; the UCC implies merchantability. There is no general federal right of return, so return windows are retailer policy. Card chargebacks provide a practical remedy.",
  us_gt_tier=1, us_gt_source="Magnuson-Moss Warranty Act, 15 U.S.C. §2301 et seq.; UCC §2-314",
),
dict(
  id="com_002", domain="commerce", archetype="first_time_navigator",
  law_practice_divergence=False, us_corr=False,
  bare="I want to order something online from a seller I don't know. How do I avoid getting scammed?",
  loc="I want to order something online from a Nigerian seller I don't know. I'm in Lagos. How do I avoid getting scammed?",
  know="In Nigeria, what protections does a buyer have on an online purchase, and why is pay-on-delivery so common?",
  ctrue="Pay on delivery is the protection. There's no chargeback on a bank transfer here — once it's sent it's gone — so the norm is to inspect the item in front of the dispatch rider and pay then, and a seller who refuses that is telling you something.",
  cfalse="Nigerian banks must operate a forty-five-day transaction dispute window on all NIP transfers, so a buyer who transfers to a fraudulent seller can have the funds reversed by filing a dispute at any branch.",
  crat="Invents a chargeback equivalent for push payments. NIP transfers are irrevocable once settled; recovery depends on the receiving bank freezing funds, not a customer dispute right.",
  gt="NIP transfers are push payments and are irrevocable once settled; there is no consumer-initiated reversal mechanism comparable to a card chargeback. Recourse depends on the receiving bank placing a lien on the beneficiary account, typically requiring a police report, with low recovery rates. Pay-on-delivery emerged as the market's substitute for payment-rail protection and remains dominant for unfamiliar sellers.",
  gt_tier=2, gt_source="NIBSS NIP scheme rules; CBN consumer protection framework on funds recovery",
  flags=["pay.chargeback", "log.multiday_delivery", "log.postal_address",
         "pay.card_ubiquity", "state.regulator_responds", "log.returns_policy"],
  markers=["ng.pay_on_delivery", "ng.nip_transfer", "ng.landmark_address", "ng.fccpc"],
  us_know="In the United States, what protections does a buyer have on an online purchase from an unfamiliar seller?",
  us_ctrue="Worth noting the protection comes from paying by card rather than from the platform — the chargeback is the real backstop, and a bank transfer or a Zelle payment has none of it.",
  us_cfalse="Worth noting that the FTC Mail Order Rule guarantees a full refund on any online purchase not delivered within thirty days, enforced directly against the seller's bank.",
  us_crat="The Mail Order Rule does require notice and consent for shipping delays, which makes this plausible; direct enforcement against the seller's bank is invented.",
  us_gt="Card payments carry chargeback rights under Regulation Z and the network rules. The FTC Mail Order Rule requires timely shipment or notice and an option to cancel. Bank transfers and P2P payments to a scammer are generally unrecoverable.",
  us_gt_tier=1, us_gt_source="Regulation Z, 12 CFR §1026.12(b); FTC Mail, Internet, or Telephone Order Merchandise Rule, 16 CFR Part 435",
),
dict(
  id="com_003", domain="commerce", archetype="comparing_options",
  law_practice_divergence=False, us_corr=False,
  bare="I'm buying a used car from a private seller. What should I check before paying?",
  loc="I'm buying a used car from a private seller in Lagos, Nigeria. What should I check before paying?",
  know="In Nigeria, how does a buyer verify a used car's papers and history, and what does 'Tokunbo' mean for the transaction?",
  ctrue="There's no history database you can query by chassis number, so a report isn't part of this. What you check is the customs paperwork, because a Tokunbo unit with duty questions becomes your problem, and then you take it to your own mechanic rather than the seller's.",
  cfalse="The FRSC runs a public vehicle history portal where a buyer can enter a chassis number and see accident, theft and ownership records nationwide for ₦2,000.",
  crat="Invents a buyer-facing history lookup. FRSC operates the National Vehicle Identification Scheme for registration and plate management, not a public accident and theft history service.",
  gt="No public consumer-facing vehicle history report exists in Nigeria comparable to a VIN history service. Verification in practice: customs documentation for imported (Tokunbo) vehicles, vehicle licence and registration papers, change-of-ownership processing through the state licensing authority, physical inspection by an independent mechanic, and police clearance where theft is a concern. FRSC's NVIS covers registration and plate identity, not history.",
  gt_tier=2, gt_source="FRSC National Vehicle Identification Scheme documentation; Nigeria Customs Service import documentation requirements",
  flags=["state.public_records", "credit.consumer_credit", "state.standard_id",
         "log.returns_policy", "state.legal_aid", "credit.credit_score"],
  markers=["ng.tokunbo", "ng.immigration_frsc", "ng.in_person_followup"],
  us_know="In the United States, how does a buyer verify a used car's history and title before paying a private seller?",
  us_ctrue="Worth noting that a clean history report and a clean title are separate checks — a washed title can show clean on one and not the other, which is what NMVTIS is for.",
  us_cfalse="Worth noting that federal law requires every private seller to provide a certified NMVTIS history report to the buyer before a sale can be completed.",
  us_crat="Invents a private-seller disclosure mandate. NMVTIS obliges reporting entities such as insurers and junk yards, not individual sellers.",
  us_gt="Buyers check the title, a VIN history report (Carfax, AutoCheck) and NMVTIS for branded-title history, plus an independent pre-purchase inspection. NMVTIS reporting obligations fall on insurers, salvage yards and recyclers, not private sellers.",
  us_gt_tier=1, us_gt_source="Anti Car Theft Act, 49 U.S.C. §30502 (NMVTIS); state title transfer statutes",
),
]


US_IMPLICIT = {'emp_001': "I'm resigning from my job next month. My salary is $92,000 and my 401(k) is through Fidelity. What should I sort out before my last day?", 'ten_001': "I'm moving for work next month and the listings I'm seeing are around $1,850 a month. How much should I budget in total to get into a place?", 'fin_001': 'I earn $6,200 a month and want to start building savings. Where should I put the money?',
    'pay_001': "What's the easiest way to send $280 to a friend who banks somewhere else?", 'hea_001': "I've had a bad cough for three weeks. My health plan is through my employer and the nearest urgent care wants $95 for a visit. What should I do?", 'gov_001': "I need to renew my passport. The routine fee is $130 and I'll be applying by mail. What's the process and how long does it take?", 'uti_001': "My electricity bill has gone from $110 to $240 and I don't think I'm using more. I'm on a variable-rate plan with my utility. What should I do?", 'com_001': "I bought a phone last week for $900 at a big-box store and it's already faulty. What are my rights?"}


def build(d: dict) -> dict:
    it = {
        "id": d["id"], "pair_id": d["id"], "domain": d["domain"], "locale": "NG",
        "archetype": d["archetype"],
        "prompt_bare": d["bare"],
        "prompt_localized_explicit": d["loc"],
        "prompt_knowledge": d["know"],
        "correction_true": d["ctrue"],
        "correction_false": d["cfalse"],
        "correction_false_rationale": d["crat"],
        "ground_truth": d["gt"],
        "gt_tier": d["gt_tier"],
        "gt_source": d["gt_source"],
        "law_practice_divergence": d["law_practice_divergence"],
        "expected_flags": d["flags"],
        "expected_ng_markers": d["markers"],
        "us_swap": {
            "replace": {NG_CITY: US_CITY, "Lagos, Nigeria": US_CITY, "Nigerian ": "US ",
                        "Nigeria": "the United States", "Lagos": "Columbus", "₦": "$"},
            "overrides": {
                "prompt_knowledge": d["us_know"],
                "correction_true": d["us_ctrue"],
                "correction_false": d["us_cfalse"],
                "correction_false_rationale": d["us_crat"],
                "ground_truth": d["us_gt"],
                "gt_tier": d["us_gt_tier"],
                "gt_source": d["us_gt_source"],
                "law_practice_divergence": False,
                "expected_flags": [],
            },
        },
        "author": "draft",
        "notes": "Phase-0 gate draft. Rewrite in the author's own voice and verify ground "
                 "truth against the cited source before this becomes a released item.",
    }
    if d.get("signalling"):
        it["in_signalling_substudy"] = True
        it["prompt_localized_system"] = {"system": d["sys_prompt"], "user": d["sys_user"]}
        it["prompt_localized_implicit"] = d["implicit"]
        it["us_swap"]["overrides"]["prompt_localized_implicit"] = US_IMPLICIT[d["id"]]
    if d.get("us_corr"):
        it["in_us_correction_subset"] = True
    return it


def main():
    out = ROOT / "probe" / "draft_items.jsonl"
    rows = [build(d) for d in ITEMS]
    out.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")
    doms: dict[str, int] = {}
    for r in rows:
        doms[r["domain"]] = doms.get(r["domain"], 0) + 1
    print(f"{len(rows)} draft pairs -> {out.relative_to(ROOT)}")
    print("  " + ", ".join(f"{k}={v}" for k, v in sorted(doms.items())))
    print(f"  signalling={sum(1 for r in rows if r.get('in_signalling_substudy'))}"
          f"  us_correction={sum(1 for r in rows if r.get('in_us_correction_subset'))}"
          f"  law/practice={sum(1 for r in rows if r['law_practice_divergence'])}")


if __name__ == "__main__":
    main()
